### ISSUE TITLE
Composer should fail if patches fail on workflows

### ISSUE THREAD

**Issue by millnut** [localgovdrupal/github_workflow_manager#9]
This might not be the place, but it saves me creating the same issue across both projects.

I think it would be great that if any patches fail rather than the current composer patches process of just continuing we should fail immediately on github actions.

This would help flag any modules where patches are no longer applying so that they can be picked up and resolved.

For the GitHub workflow on the composer step/s we should only need to add an environment variable called `COMPOSER_EXIT_ON_PATCH_FAILURE` with a value of `1`

Thoughts on this @finnlewis @stephen-cox @ekes

**Comment by ekes** [comment]
Nice one. If I recall correctly we did have it failing _generally_ but as people didn't make changes for their deploys this was causing too much pain. Being able to change it for just _testing_ only makes complete sense to me.

**Comment by finnlewis** [comment]
If we can make sure it only fails on GitHub, that will avoid causing pain for people in the wild. 

Sounds like the motivation to force ourselves to address outdated patches ASAP, which I think is a good idea.

**Comment by millnut** [comment]
@ekes @finnlewis yep this will be purely a GitHub action only not added to the composer.json or anything like that to affect users. Just a dev process thing to catch failing patches easier. I'll put a PR together for both the project and microsites_project repos.

**Comment by millnut** [comment]
Closing as this is now merged into 3.x
